[package]
name = "random-forust"
version = "0.1.0"
authors = ["Alfonso Ros <alfonsoros88@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6"

[[bin]]
name = "xor"
path = "examples/xor/main.rs"
